// Styles >>
import "./globals.css";
import { Montserrat } from "next/font/google";
// Metadata >>
import type { Metadata } from "next";
// Redux Provider >>
import StoreProvider from "@/app/redux/StoreProvider";
// Static Components >>
import NavBar from "@/app/components/server/NavBar";
import Alert from "./components/client/Alert";
import AuthChanged from "./firebase/AuthChanged";

const fontVariable = Montserrat({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${fontVariable.className} antialiased flex ml-0 sm:ml-20 pt-6 px-6 pb-28 md:pb-6`}>
        <StoreProvider>
          <AuthChanged />
          <Alert />
          <NavBar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
